### ISSUE TITLE
Credentials IDA Tutor Support

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/credentials#1761]
Currently, there is no official tutor-credentials plugin. There is a community one, but it is out of date and the docker image seems to be missing: https://github.com/pcliupc/tutor-credentials

There is an [issue that was closed accepting this plugin](https://github.com/overhangio/2u-tutor-adoption/issues/39) as the official community plugin for credentials.

It looks at though the plugin has not been touched since it was created.

**Comment by ghassanmas** [comment]
There is other plugin which I think is similar to the one you referred above: https://github.com/lpm0073/tutor-contrib-credentials

**Comment by kdmccormick** [comment]
This was done at some point: https://github.com/overhangio/tutor-credentials/
