### ISSUE TITLE
Sync failures between platform & Credentials

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/credentials#1762]
The current jenkins jobs for copying course certificate data to Credentials are unreliable and result in data drift.

**Comment by hurtstotouchfire** [comment]
One update on this -- enabling the event bus should help with these issues. We have enabled it for edx.org.

**Comment by deborahgu** [comment]
over the last 2 years a lot of improvements have been made to this job and it is much more reliable than it was before. We will reopen with specific problems when we have more.
