### ISSUE TITLE
Upgrade Credentials to Node 16

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/credentials#1791]
- [ ] https://github.com/openedx/credentials/issues/1792
- [x] Fix https://github.com/openedx/credentials-themes/issues/474

**Comment by abdullahwaheed** [comment]
@hurtstotouchfire i think #1817 resolves #1792, should we close this?

**Comment by justinhynes** [comment]
The Node 16 upgrade has been completed for some time. Closing issue.
