### ISSUE TITLE
Remove bok-choy usage

### ISSUE THREAD

**Issue by kdmccormick** [openedx/credentials#1989]
This repo's acceptance tests still use the bok-choy framework, which [was deprecated in Feb 2022](https://github.com/openedx/public-engineering/issues/13). The bok-choy repository is no longer being maintained, and it will soon be archived.

Once the bok-choy repo is archived, the acceptance tests should continue working, as we will not be removing the package's releases from PyPI. For long-term maintainability of this repo, though, the tests should eventually be upgraded to a non-bok-choy testing framework or removed.

**Comment by dianakhuang** [comment]
This removal may be blocked on the work to move the frontend code in credentials into an MFE.

We may also want to evaluate the existing credentials tests to see if we even feel like these bok choy tests are useful.

**Comment by feanil** [comment]
@hurtstotouchfire can you help schedule this work, no rush but it just needs to get done.

**Comment by feanil** [comment]
@hurtstotouchfire FYI, we're planning on archiving the bok-choy repo in the next month.  It will not receive any further updates after that including security updates.  If your acceptance tests are still valuable, we strongly recommend moving them to a different testing framework.

**Comment by hurtstotouchfire** [comment]
Thanks @feanil, adding this to our triage queue.

**Comment by jsnwesson** [comment]
A Jira ticket was created to address this and we'll be bringing this up in our next grooming session.

**Comment by jsnwesson** [comment]
Update: this task is now prioritized and should hopefully be worked on in the upcoming weeks.
