### ISSUE TITLE
Replace MemcachedCache backend with PymemcacheCache 

### ISSUE THREAD

**Issue by iamsobanjaved** [openedx/credentials#2144]
The django.core.cache.backends.memcached.MemcachedCache backend is removed so we now are replacing this with `PymemcacheCache` in all of our IDAs, so we need to replace this for credentials also.

https://docs.djangoproject.com/en/4.2/releases/4.1/#features-removed-in-4-1

```[tasklist]
### Update in following environments
- [x] devstack
- [x] stage
- [x] production
- [x] edge
- [x] sandbox
```

**Comment by mumarkhan999** [comment]
Things to be done:
- First, add pymemcache dependency in the codebase and move it to PROD 
- Update the relevant configs for sandbox in sandbox-internal
- Update the relevant configs for stage in edx-internal
- Update the relevant configs for prod in edx-internal
- Update the relevant configs for edge in edge-internal
- Update the configs in related codebase so that the docker images of that service also get updated

**Comment by mumarkhan999** [comment]
These are the config related changes which we will do:
- Update the backend
    - https://github.com/edx/sandbox-internal/blob/master/sandbox-remote-config/sandbox/lms.yml#L58
- Add extra parameters for pymemcache hashclient to enable pooling. It will make the client thread-safe.
    - https://github.com/edx/sandbox-internal/blob/master/sandbox-remote-config/sandbox/lms.yml#L63-L66

**Comment by mumarkhan999** [comment]
One more thing to add:

- The IDA/services which are using [edx-django-utils](https://github.com/openedx/edx-django-utils) as their `direct-dependency`. We will enable `edx_django_utils.cache.disable_forced_cache_miss_for_none` waffle switch for them from their admin panel [link to doc](https://github.com/openedx/edx-django-utils/blob/7683febaa1e6cbe628ffa850befe0f67b7bfcc77/CHANGELOG.rst#L24)

**Comment by justinhynes** [comment]
@iamsobanjaved & @UsamaSadiq 

I believe this work has been completed some time ago. Is there any reason to keep the issue open? Is there any remaining work to be done here?

**Comment by iamsobanjaved** [comment]
Thanks for reminding, closed the issue
